### ISSUE TITLE
Grammar load failure Asterisk 13 Centos

### ISSUE THREAD

**Issue by adeshpandey** [unispeech/asterisk-unimrcp#12]
Hi I have successfully installed unimrcp client,server and unimrcp asterisk on my new centOS 7 server with Asterisk but when I try to use speech recognition I can not perform because it says that grammar load failure. Here is my dialplan given below:

```
exten => 1235,1,Answer
exten => 1235,n,MRCPRecog(builtin:grammar/number,p=default&t=5000&b=1&ct=0.7&spl=en-US&f=hello-world)
same=>n,Verbose(1, ${RECOGSTATUS}, ${RECOG_COMPLETION_CAUSE},${RECOG_RESULT})
exten => 1235,Hangup

```
and the error what I receive is : 
```
builtin:grammar/number
[Jun 10 08:34:07] NOTICE[2440]: src/mrcp_client_connection.c:633 : Receive MRCPv2 Data 10.0.0.117:48704 <-> 10.0.0.117:1544 [125 bytes]
MRCP/2.0 125 1 406 COMPLETE
Channel-Identifier: 6b2df9bddc39466b@speechrecog
Completion-Cause: 004 grammar-load-failure


[Jun 10 08:34:07] NOTICE[2439]: src/mrcp_client_session.c:498 : Raise App MRCP Response ASR-10 <6b2df9bddc39466b>
[Jun 10 08:34:07] ERROR[2755][C-00000010]: app_mrcprecog.c:1304 app_recog_exec: (ASR-10) Unable to start recognition
```

**Comment by achaloyan** [comment]
If you are using the UniMRCP server with the GSR plugin, then consider specifying a builtin gramma as follows: builtin:**speech**/$name.

Your MRCPRecog would look like:

`MRCPRecog(builtin:speech/number,p=default&t=5000&b=1&ct=0.7&spl=en-US&f=hello-world)`
