### ISSUE TITLE
Crash on Failure on SpeechEngine

### ISSUE THREAD

**Issue by scgm11** [unispeech/asterisk-unimrcp#13]
Im having crahes easy to reproduce when the Speech engine crashes or stops.

Ubuntu 16.04, Asterisk 13.16, Verbio Engine

usage example:
exten=> _123,1,Answer()
exten=> _123,2,SpeechCreate(unimrcp)
exten=> _123,3,SpeechLoadGrammar(grammar,/usr/local/unimrcp/data/grammar.xml)
exten=> _123,4,SpeechActivateGrammar(grammar)
exten=> _123,5,SpeechBackground(MYSOUND},2)
exten=> _123,6,SpeechDeactivateGrammar(grammar)
exten=> _123,7,SpeechDestroy()

When I stop the Verbio Server I get a crash of unimrcp
Attached btfull of the core dump, this is easy to reproduce having 

[btfull.txt](https://github.com/unispeech/asterisk-unimrcp/files/1114906/btfull.txt)

**Comment by achaloyan** [comment]
Well, indeed. Session object should have been referenced instead of channel. Fixed in 68bebdd8101179463576f850c1ac8b96104cd3b7
