### ISSUE TITLE
Not moving to next sound if RIFF headers present

### ISSUE THREAD

**Issue by scgm11** [unispeech/asterisk-unimrcp#14]
If the audio file to reproduce has RIFF headers

Example:
WAVE properties:

  Non-canonical header:       yes

  Extra RIFF chunks:          yes (2692 bytes)

the length of the sound is not correctly recognized so will stop at the first sound and wont pass to the next one, removing this header using sox fix the issue but I think it should get the Extra RIFF chunks and add it in

app_mrcprecog.c . line 1348

if (read_filelength + read_filestep > max_filelength) {....

so it knows the file is over

what do you think?

**Comment by achaloyan** [comment]
This issue is the outcome of the following discussion

https://groups.google.com/forum/#!topic/unimrcp/MmMuRkoZ1JY

**Comment by achaloyan** [comment]
Fixed in https://github.com/unispeech/asterisk-unimrcp/commit/b2494545bf4622057a83330692673a8bd3adff33.
