### ISSUE TITLE
error: Externally compiled modules must declare AST_MODULE_SELF_SYM.

### ISSUE THREAD

**Issue by iqnr** [unispeech/asterisk-unimrcp#15]
Hi,

I'm new to MRCP. I have the same problem as Amitaj. https://groups.google.com/forum/#!topic/unimrcp/xQDV4biw3S4

When I try to install the asterisk-unimrcp bridge, I run into compilation error.

# ./configure 
.....
.....
****************************** REPORT ******************************

Asterisk version.............. : 14.3.0
UniMRCP version............... : 1.4.0
UniMRCP modules version....... : 1.4.0

Compiler...................... : gcc
Compiler flags................ : -g -O2
Preprocessor definitions...... :
Linker flags.................. :

Modules install path...........: /usr/lib/asterisk/modules
Configuration install path.....: /etc/asterisk
XML doc install path...........: /var/lib/asterisk/documentation/thirdparty

Speech resource module.........: yes
Application module.............: yes

********************************************************************

# make 
Making all in res-speech-unimrcp
make[1]: Entering directory `/usr/src/asterisk-unimrcp-1.4.0/res-speech-unimrcp'
  CC       res_speech_unimrcp.lo
In file included from ../include/ast_compat_defs.h:30:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk.h:300:2: error: #error "Externally compiled modules must d                                                                                                             eclare AST_MODULE_SELF_SYM."
 #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."
  ^
res_speech_unimrcp.c:31:1: error: expected declaration specifiers or ‘...’ befor                                                                                                             e string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
 ^
res_speech_unimrcp.c:31:33: error: expected declaration specifiers or ‘...’ befo                                                                                                             re string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
                                 ^
make[1]: *** [res_speech_unimrcp.lo] Error 1
make[1]: Leaving directory `/usr/src/asterisk-unimrcp-1.4.0/res-speech-unimrcp'
make: *** [all-recursive] Error 1

Do you have any updates on this problem?

**Comment by achaloyan** [comment]
Thanks for posting this as a separate issue. There has been no update yet: Asterisk 14 is not supported as of now.

**Comment by achaloyan** [comment]
Fixed in d8ff74d4236e60b79dcf2479f2680f5188b4de26. A new release will be produced in a couple of days.

**Comment by siptain** [comment]
Hi Guys,

It looks, I have the same problem, however not able to run MRCP module. Using Asterisk 16:
Please can some one help me out: Thanks

In file included from ../include/ast_compat_defs.h:45:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk.h:232:2: error: #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."
 #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."
  ^
In file included from res_speech_unimrcp.c:28:0:
../include/ast_compat_defs.h:118:23: error: conflicting types for 'ast_channel_set_readformat'
 static APR_INLINE int ast_channel_set_readformat(struct ast_channel *chan, ast_format_compat *format)
                       ^
In file included from ../include/ast_compat_defs.h:47:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk/channel.h:4300:6: note: previous declaration of 'ast_channel_set_readformat' was here
 void ast_channel_set_readformat(struct ast_channel *chan, struct ast_format *format);
      ^
In file included from res_speech_unimrcp.c:28:0:
../include/ast_compat_defs.h:122:23: error: conflicting types for 'ast_channel_set_writeformat'
 static APR_INLINE int ast_channel_set_writeformat(struct ast_channel *chan, ast_format_compat *format)
                       ^
In file included from ../include/ast_compat_defs.h:47:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk/channel.h:4301:6: note: previous declaration of 'ast_channel_set_writeformat' was here
 void ast_channel_set_writeformat(struct ast_channel *chan, struct ast_format *format);
      ^
res_speech_unimrcp.c:31:1: error: expected declaration specifiers or '...' before string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
 ^
res_speech_unimrcp.c:31:33: error: expected declaration specifiers or '...' before string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
                                 ^
res_speech_unimrcp.c:42:28: fatal error: unimrcp_client.h: No such file or directory
 #include <unimrcp_client.h>
                            ^
compilation terminated.
make[1]: *** [res_speech_unimrcp.lo] Error 1
make[1]: Leaving directory `/usr/src/uni-ast-package-1.1.0/modules/res-speech-unimrcp'
make: *** [all-recursive] Error 1
Making install in res-speech-unimrcp
make[1]: Entering directory `/usr/src/uni-ast-package-1.1.0/modules/res-speech-unimrcp'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"asterisk-unimrcp\" -DPACKAGE_TARNAME=\"asterisk-unimrcp\" -DPACKAGE_VERSION=\"1.1.0\" -DPACKAGE_STRING=\"asterisk-unimrcp\ 1.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"asterisk-unimrcp\" -DVERSION=\"1.1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DUNIMRCP_DIR_LOCATION=\"/usr/local/unimrcp\" -DASTERISK_MAJOR_VERSION=16 -DASTERISK_MINOR_VERSION=4 -DASTERISK_PATCH_VERSION=1 -I. -I../include -D_REENTRANT -D_GNU_SOURCE -g -O2 -pthread -I/usr/local/unimrcp/include -I/usr/local/unimrcp/include/apr-1   -I/usr/include    -g -O2 -MT res_speech_unimrcp.lo -MD -MP -MF .deps/res_speech_unimrcp.Tpo -c -o res_speech_unimrcp.lo res_speech_unimrcp.c
libtool: compile:  gcc -DPACKAGE_NAME=\"asterisk-unimrcp\" -DPACKAGE_TARNAME=\"asterisk-unimrcp\" -DPACKAGE_VERSION=\"1.1.0\" "-DPACKAGE_STRING=\"asterisk-unimrcp 1.1.0\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"asterisk-unimrcp\" -DVERSION=\"1.1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DUNIMRCP_DIR_LOCATION=\"/usr/local/unimrcp\" -DASTERISK_MAJOR_VERSION=16 -DASTERISK_MINOR_VERSION=4 -DASTERISK_PATCH_VERSION=1 -I. -I../include -D_REENTRANT -D_GNU_SOURCE -g -O2 -pthread -I/usr/local/unimrcp/include -I/usr/local/unimrcp/include/apr-1 -I/usr/include -g -O2 -MT res_speech_unimrcp.lo -MD -MP -MF .deps/res_speech_unimrcp.Tpo -c res_speech_unimrcp.c  -fPIC -DPIC -o .libs/res_speech_unimrcp.o
In file included from ../include/ast_compat_defs.h:45:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk.h:232:2: error: #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."
 #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."
  ^
In file included from res_speech_unimrcp.c:28:0:
../include/ast_compat_defs.h:118:23: error: conflicting types for 'ast_channel_set_readformat'
 static APR_INLINE int ast_channel_set_readformat(struct ast_channel *chan, ast_format_compat *format)
                       ^
In file included from ../include/ast_compat_defs.h:47:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk/channel.h:4300:6: note: previous declaration of 'ast_channel_set_readformat' was here
 void ast_channel_set_readformat(struct ast_channel *chan, struct ast_format *format);
      ^
In file included from res_speech_unimrcp.c:28:0:
../include/ast_compat_defs.h:122:23: error: conflicting types for 'ast_channel_set_writeformat'
 static APR_INLINE int ast_channel_set_writeformat(struct ast_channel *chan, ast_format_compat *format)
                       ^
In file included from ../include/ast_compat_defs.h:47:0,
                 from res_speech_unimrcp.c:28:
/usr/include/asterisk/channel.h:4301:6: note: previous declaration of 'ast_channel_set_writeformat' was here
 void ast_channel_set_writeformat(struct ast_channel *chan, struct ast_format *format);
      ^
res_speech_unimrcp.c:31:1: error: expected declaration specifiers or '...' before string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
 ^
res_speech_unimrcp.c:31:33: error: expected declaration specifiers or '...' before string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
                                 ^
res_speech_unimrcp.c:42:28: fatal error: unimrcp_client.h: No such file or directory
 #include <unimrcp_client.h>
                            ^
compilation terminated.
make[1]: *** [res_speech_unimrcp.lo] Error 1
make[1]: Leaving directory `/usr/src/uni-ast-package-1.1.0/modules/res-speech-unimrcp'
make: *** [install-recursive] Error 1
