### ISSUE TITLE
deadlock on latest release

### ISSUE THREAD

**Issue by scgm11** [unispeech/asterisk-unimrcp#17]
Im experiencing a deadlock with the latest release 1.5

Channel              Context              Extension        Prio State   Application  Data                      CallerID        Duration Accountcode PeerAccount BridgeID
SIP/QUALITY1-0000005 functions            FUNC_DIGITE_O_DI    5 Up      MRCPRecog    "/usr/local/unimrcp/data/ 912732278       07:26:42 QUALITY1

attached traces I will compile it with better debug options and add them

[core-asterisk-running-2017-09-07T16-59-48+0200-brief.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285134/core-asterisk-running-2017-09-07T16-59-48.0200-brief.txt)
[core-asterisk-running-2017-09-07T16-59-48+0200-full.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285131/core-asterisk-running-2017-09-07T16-59-48.0200-full.txt)
[core-asterisk-running-2017-09-07T16-59-48+0200-locks.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285132/core-asterisk-running-2017-09-07T16-59-48.0200-locks.txt)
[core-asterisk-running-2017-09-07T16-59-48+0200-thread1.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285133/core-asterisk-running-2017-09-07T16-59-48.0200-thread1.txt)

**Comment by scgm11** [comment]
Seems to there is no deadlock but anyway the channel is stuck, seems to be when a grammar cant be loaded

 ERROR[32387][C-00000005]: app_mrcprecog.c:1203 app_recog_exec: (ASR-13) Unable to load grammar

then the channel get stuck

[core-asterisk-running-2017-09-07T19-51-35+0200-brief.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285653/core-asterisk-running-2017-09-07T19-51-35.0200-brief.txt)
[core-asterisk-running-2017-09-07T19-51-35+0200-full.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285651/core-asterisk-running-2017-09-07T19-51-35.0200-full.txt)
[core-asterisk-running-2017-09-07T19-51-35+0200-locks.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285652/core-asterisk-running-2017-09-07T19-51-35.0200-locks.txt)
[core-asterisk-running-2017-09-07T19-51-35+0200-thread1.txt](https://github.com/unispeech/asterisk-unimrcp/files/1285654/core-asterisk-running-2017-09-07T19-51-35.0200-thread1.txt)

**Comment by achaloyan** [comment]
Could you provide Asterisk/UniMRCP logs with debug log level enabled. 
I assume you have built everything from source, right. Just in case, what version of Asterisk do you use?

**Comment by scgm11** [comment]
it's not really a deadlock the log I will attach I think is very clear, the channels is waiting for a timeout maybe some issue on the backend anyway I think should clear the channel earlier even asterisk cant't hangup the call or cant manually hangup request (channel) but I dont see any lock hold as I show on the low.

Maybe is an engine  issue but didnt happend on the previouse version or at least not as usual to be aware of.
ast 13.17

[log.txt](https://github.com/unispeech/asterisk-unimrcp/files/1286000/log.txt)

**Comment by achaloyan** [comment]
I doubt this issue is related to the latest release. Actually, there is no response to session termination request. The following log statement is a very bad indication, anyway.

speech_channel.c:370 speech_channel_destroy: (ASR-57) **MRCP session has not terminated after** 30000 ms

If you enable UniMRCP client logs (set log-level to DEBUG in mrcp.conf), I'll tell you what is going on precisely. Most likely there is no response from the MRCP server you use.

**Comment by scgm11** [comment]
Ill try to reproduce it again I haven't been able yet, Im closing the issue for the time being I will reopen if needed.

**Comment by scgm11** [comment]
Im seeing this in a loaded environment that is hard to get all the debug, anyway why cant I hangup request the call? is there no global timeout that can be added so in case not response hangup the channel?

**Comment by achaloyan** [comment]
If you set the request-timeout in mrcp.conf, for example, to 5000 msec, then any request with no response received within the specified timeout will be cancelled. As a result, the channel will ultimately hang up.

**Comment by scgm11** [comment]
channels are not releasing even with the request-timeout feature, I will try to get more log

**Comment by scgm11** [comment]
attached full log of a call that the channel get stuck, even with the timeout params


[fulllog.txt](https://github.com/unispeech/asterisk-unimrcp/files/1324330/fulllog.txt)

**Comment by achaloyan** [comment]
While I could not find anything obviously wrong in the attached txt files, it is interesting what happened after the last log statement that you dumped in the comments.

[Sep 22 13:42:23] DEBUG[21630][C-00000049]: src/apt_task.c:263 : Signal Message to [MRCP Client] [0x7f344c01de80;4;0] 

For every Signal Message, there should be a Process Message. If you have the remaining logs, look for  0x7f344c01de80;4;0 if you can see it there. 

You may also to track thread identifiers. Process Message should have been called from [21043], and in your logother.txt I can see that this thread continues to process messages, but there is a gap from Sep 22 13:42:23 to Sep 22 13:48:32. Not sure what happened in the meantime.

Needless to say, it is also interesting what happened with thread [21630]. Do you see any logs from this thread afterwards.

**Comment by scgm11** [comment]
I attach the logs

[0x7f344.txt](https://github.com/unispeech/asterisk-unimrcp/files/1326231/0x7f344.txt)
[21043.txt](https://github.com/unispeech/asterisk-unimrcp/files/1326230/21043.txt)
[21630.txt](https://github.com/unispeech/asterisk-unimrcp/files/1326232/21630.txt)

**Comment by achaloyan** [comment]
Well, now I can track this session to the end, and there is nothing wrong in this flow, besides the fact that channel_opened returned error, which is OK. MRCPRecog did complete in all these cases. Why would you think that your problem is MRCP-related.

**Comment by scgm11** [comment]
Because the channel gets stuck at MRCPRecog, and even when I see a hangup the channel is still stuck there... and cant even hangup request....

**Comment by achaloyan** [comment]
OK, then provide the identified of a stuck channel along with the logs. 

In all the attempts I have seen so far, MRCPRecog() did exit. Here is the last statement which you may track

**MRCPRecog() exiting**
