### ISSUE TITLE
Module not loading with Asterisk 15.2

### ISSUE THREAD

**Issue by olivierb2** [unispeech/asterisk-unimrcp#23]
Dear community,

I'm using Asterisk 15.2 on a Wazo distribution. While this Asterisk uniMRCP is compiling correctly, I'm unable to load it from Asterisk.

```
xivo*CLI> module load res_speech_unimrcp.so
Unable to load module res_speech_unimrcp.so
Command 'module load res_speech_unimrcp.so' failed.
[Feb 23 09:54:26] WARNING[7365]: loader.c:580 load_dlopen: Error loading module 'res_speech_unimrcp.so': /usr/lib/asterisk/modules/res_speech_unimrcp.so: undefined symbol: ast_speech_change_state
[Feb 23 09:54:26] WARNING[7365]: loader.c:1184 load_resource: Module 'res_speech_unimrcp.so' could not be loaded.
```

The other module app_unimrcp.so is loading correctly.

I'm not developper and able to provide a fix. Does anybody is able to propose a patch for this issue?

Thanks

Obitwo

**Comment by achaloyan** [comment]
Dear Oliver,

While I am not familiar with Wazo, this issue might be caused by having different versions of the Asterisk development package (headers and libraries) that the UniMRCP modules are built with, and the Asterisk itself.

If this is a Debian-based distribution, then what is the output of 

`apt --installed list | grep asterisk`

**Comment by olivierb2** [comment]
Here the output of the command requested

asterisk/unknown,now 8:15.2.0-1~wazo4.deb9 amd64  [installé, automatique]
asterisk-dev/unknown,now 8:15.2.0-1~wazo4.deb9 all  [installé]
asterisk-sounds-main/unknown,now 8:15.2.0-1~wazo4.deb9 all  [installé, automatique]
asterisk-sounds-wav-en-us/unknown,now 1:17.17~20171123.144644.8d6ef03 all  [installé, automatique]
asterisk-sounds-wav-fr-fr/unknown,now 1:17.17~20171123.144644.8d6ef03 all  [installé, automatique]
python-asterisk-ari/unknown,now 0.3.0-1 all  [installé, automatique]

**Comment by achaloyan** [comment]
Not sure about Wazo, but I just installed Asterisk 15.2.2 from source and also built UniMRCP modules against. Everything works as intended. 

There are no API changes in Asterisk 15.2 which may cause incompatibility issues with modules built externally.

**Comment by olivierb2** [comment]
Thanks for the information, I will made further testing, I close this ticket as it seems not related to newest version.

**Comment by Panshuyang** [comment]
Dear community,

I'm using Asterisk 1.4 ,While this Asterisk UNIMRCP 1.1.0 is compiling correctly, I'm unable to load it from Asterisk, and got load Error message as below:
`
[Mar 22 11:53:01] WARNING[25676] loader.c: Error loading module 'app_unimrcp.so': /usr/lib/asterisk/modules/app_unimrcp.so: undefined symbol: ast_datastore_alloc
[Mar 22 11:53:01] WARNING[25676] loader.c: Module 'app_unimrcp.so' could not be loaded.
`
how can i fix this?
