### ISSUE TITLE
Return values from ${RECOG_COMPLETION_CAUSE}

### ISSUE THREAD

**Issue by IraComm** [unispeech/asterisk-unimrcp#25]
All the help files for Asterisk for the SynthAndRecog "**${RECOG_COMPLETION_CAUSE}**"  has only 3 values: 000=success, 001=No Match, 002=No Input.
What is the meaning of 003? And, are there any others?

same => n,gotoif($[${RECOG_COMPLETION_CAUSE}=001]?BadMenu)
same => n,gotoif($[${RECOG_COMPLETION_CAUSE}=002]?NoInput)

**Comment by achaloyan** [comment]
This variable is set based on the corresponding header filed Completion-Cause set in a RECOGNITION-COMPLETE event. Possible completion cause codes and their interpretation slightly differ for MRCP v1 and v2 and can be found at the following links.

https://tools.ietf.org/html/rfc4463#section-8.4.8
https://tools.ietf.org/html/rfc6787#section-9.4.11

**Comment by IraComm** [comment]
Fantastic. Thanks for the info.

 

Ira S. Holden III

O/C: 513-631-4244
