### ISSUE TITLE
/usr/bin/install: cannot stat '.libs/res_speech_unimrcp.lai': No such file or directory

### ISSUE THREAD

**Issue by Jeffrey1207** [unispeech/asterisk-unimrcp#26]
when I execute the make install
os will throw an error for me, and the installation failed.

for detail:

root@asterisk_server:/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1# ./bootstrap 
+ libtoolize --force --automake --copy
+ aclocal -I build/acmacros
+ automake --foreign --add-missing --copy
configure.ac:37: installing 'build/compile'
configure.ac:29: installing 'build/missing'
app-unimrcp/Makefile.am: installing 'build/depcomp'
+ autoconf
+ rm -rf autom4te.cache

root@asterisk_server:/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1# ./configure --with-unimrcp=/opt/unimrcp/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for C compiler vendor... gnu
checking for pkg-config... /usr/bin/pkg-config
configure: UniMRCP configuration
1.5.0
configure: Asterisk configuration
15.6.1
configure: enable maintainer mode: no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating res-speech-unimrcp/Makefile
config.status: creating app-unimrcp/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

****************************** REPORT ******************************

Asterisk version.............. : 15.6.1
UniMRCP version............... : 1.5.0
UniMRCP modules version....... : 1.5.1

Compiler...................... : gcc
Compiler flags................ : -g -O2
Preprocessor definitions...... :
Linker flags.................. :

Modules install path...........: /usr/lib/asterisk/modules
Configuration install path.....: /etc/asterisk
XML doc install path...........: /var/lib/asterisk/documentation/thirdparty

Speech resource module.........: yes
Application module.............: yes

********************************************************************

root@asterisk_server:/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1# make
Making all in res-speech-unimrcp
make[1]: Entering directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
Making all in app-unimrcp
make[1]: Entering directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/app-unimrcp'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/app-unimrcp'
make[1]: Entering directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1'

root@asterisk_server:/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1# make install
Making install in res-speech-unimrcp
make[1]: Entering directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
make[2]: Entering directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
make[2]: Nothing to be done for 'install-exec-am'.
test -d /etc/asterisk || /bin/bash /usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/build/install-sh -d /etc/asterisk
test -f /etc/asterisk/res-speech-unimrcp.conf || /usr/bin/install -c -m 644 ../conf/res-speech-unimrcp.conf /etc/asterisk
 /bin/mkdir -p '/usr/lib/asterisk/modules'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   res_speech_unimrcp.la '/usr/lib/asterisk/modules'
libtool: install: /usr/bin/install -c .libs/res_speech_unimrcp.so /usr/lib/asterisk/modules/res_speech_unimrcp.so
libtool: install: /usr/bin/install -c .libs/res_speech_unimrcp.lai /usr/lib/asterisk/modules/res_speech_unimrcp.la
/usr/bin/install: cannot stat '.libs/res_speech_unimrcp.lai': No such file or directory
Makefile:385: recipe for target 'install-modLTLIBRARIES' failed
make[2]: *** [install-modLTLIBRARIES] Error 1
make[2]: Leaving directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
Makefile:552: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
Makefile:422: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

Can you provide any solution for me to solve the issues

**Comment by achaloyan** [comment]
The procedure is generally correct. It is not clear why there was "Nothing to be done for all" in res-speech-unimrcp and app-unimrcp directories. Perhaps this was not a clean run and you had already built them before.

root@asterisk_server:/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1# make
Making all in res-speech-unimrcp
make[1]: Entering directory '/usr/local/src/asterisk-unimrcp-asterisk-unimrcp-1.5.1/res-speech-unimrcp'
make[1]: Nothing to be done for 'all'.

As for the error itself, something went wrong with libtool. What Linux distribution is this? What are the versions of libtool and gcc?

**Comment by Jeffrey1207** [comment]
I'm using Ubuntu 18.04 LTS.

**Comment by achaloyan** [comment]
Then the question is how you installed UniMRCP. Note that UniMRCP binary packages are currently available for Ubuntu 16.04 but not 18.04. You may need to install UniMRCP from source.
