### ISSUE TITLE
undefined symbol: ast_datastore_alloc

### ISSUE THREAD

**Issue by Panshuyang** [unispeech/asterisk-unimrcp#31]
Dear community,

I'm using Asterisk 1.4 ,While this Asterisk UNIMRCP 1.1.0 is compiling correctly, I'm unable to load it from Asterisk, and got load Error message as below:
[Mar 22 11:53:01] WARNING[25676] loader.c: Error loading module 'app_unimrcp.so': /usr/lib/asterisk/modules/app_unimrcp.so: undefined symbol: ast_datastore_alloc 
[Mar 22 11:53:01] WARNING[25676] loader.c: Module 'app_unimrcp.so' could not be loaded.
how can i fix this?

**Comment by achaloyan** [comment]
Asterisk 1.4 has not been supported for a while.
