### ISSUE TITLE
Audible pop when playing wav file using MRCPRecog

### ISSUE THREAD

**Issue by DRoet** [unispeech/asterisk-unimrcp#32]
Hi, I somehow bumped into the following problem:

When you use the MRCPrecog function to play a .wav prompt containing a [fact chunk](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html) header it shows a debug line in the asterisk console:
`[Jul  2 16:59:04] DEBUG[640][C-00000029]: format_wav.c:192 check_header: Skipping unknown block 'fact'`

However this also causes a small "popping" sound at the start of the prompt, which is really annoying for the end user.

Playing the same prompt in the Asterisk PLAYBACK function causes no issues.

wondering if anyone can help me with this...

**Comment by achaloyan** [comment]
MRCPRecog() uses Asterisk functions ast_openstream() with further reference to ast_playstream() to play a prompt while performing recognition. See the function [astchan_stream_file](https://github.com/unispeech/asterisk-unimrcp/blob/master/app-unimrcp/speech_channel.c#L744). Based on your description, I would guess this method does not properly skip the fact chunk, whereas Playback() uses ast_streamfile() internally. So, this issue belongs to Asterisk.
