### ISSUE TITLE
Empty recorded audio file from MRCPSynth 

### ISSUE THREAD

**Issue by aleksov** [unispeech/asterisk-unimrcp#4]
Greetings,

I use 'f' option of MRCPSynth to store synthesized audio in file but resulting file is empty. Audio generates correctly and I can hear it.

I am not sure but I think the reason is not writing data in app_mrcpsynth.c. fd is opened at line 567 and then closed at 472 without using.

Example:
```same  =>      n, MRCPSynth("Testing",f=synthtestrecord)```

Everything works in asterisk-unimrcp-1.3.0

Versions:
Asterisk 11.22.0
unimrcp-1.3.0
asterisk-unimrcp-1.3.1

**Comment by achaloyan** [comment]
Greetings,

Your observations are correct. This is a regression introduced in the following commit c02bbd8f327f3ab639e4136268ead9b41a5b663f.

Needs to be fixed...
