### ISSUE TITLE
Asterisk 17 support

### ISSUE THREAD

**Issue by DRoet** [unispeech/asterisk-unimrcp#40]
When I try to setup asterisk 17 with unimrcp I get the following error:

```sh
cd asterisk-unimrcp-1.5.2/
./configure
make
make install

....
configure: UniMRCP configuration
1.6.0
configure: Asterisk configuration
17.0.1
configure: error: Could not find asterisk.h, make sure Asterisk development package is installed
````

**Comment by achaloyan** [comment]
Ho did you install Asterisk 17. If you installed from source, then consider using `make install-headers`, which would install the missing header files.

In former versions of Asterisk, this directive is called implicitly with `make install`.

**Comment by DRoet** [comment]
ah gotcha.
yeah I am installing from source so that's probably it, thanks!

**Comment by saikiahemant** [comment]
`configure: UniMRCP configuration
1.7.0
configure: Asterisk configuration
17.9.3
configure: error: Could not find asterisk.h, make sure Asterisk development package is installed`

I am getting the same error. The file asterisk.h is present in /usr/include. But I still receive this error.

**Comment by achaloyan** [comment]
What is the full output of configure?
