### ISSUE TITLE
ERROR[17116][C-00029668] app_mrcprecog.c: (ASR-759827) Recognition terminated prematurely

### ISSUE THREAD

**Issue by jfranco1989** [unispeech/asterisk-unimrcp#43]
Hi all!

I have one server with Asterisk with ASR service Verbio, in this environment I have a high flow of calls and at peak times I receive the log below and the recognition does not start.

[Jul 30 13:40:50] WARNING[17116][C-00029668] audio_queue.c: (ASR-759827) Audio queue overflow!
[Jul 30 13:40:50] ERROR[17116][C-00029668] app_mrcprecog.c: (ASR-759827) Recognition terminated prematurely
[Jul 30 13:40:50] WARNING[17116][C-00029668] app_mrcprecog.c: (ASR-759827) Unable to retrieve result
[Jul 30 13:40:51] NOTICE[17116][C-00029668] app_mrcprecog.c: MRCPRecog() exiting status: ERROR on PJSIP/sbc_endpoint-00029668

Any idea what it might be?

Best Regards!

**Comment by achaloyan** [comment]
Hi

What version of UniMRCP modules for Asterisk do you use? I vaguely remember a similar issue fixed a year or two ago. Look through the commit logs or closed issues to find out more details.

**Comment by jfranco1989** [comment]
Hi Achaloyan,

I'm using 1.5.

**Comment by achaloyan** [comment]
You may consider using the latest release such as 1.7.0 or clone the source from the repository.
