### ISSUE TITLE
DTMF duplication

### ISSUE THREAD

**Issue by hamel1on** [unispeech/asterisk-unimrcp#44]
Hello.
There is a dump with a problem in the attachment. The problem appears to be due to a long DTMF signal from the upstream station. Unimrcp takes one button for two.
[1.zip](https://github.com/unispeech/asterisk-unimrcp/files/5034813/1.zip)

**Comment by achaloyan** [comment]
Hello,

Quickly looking through RTP events in the provided network capture, I suspect the problem must be in the way the events are sent. In particular, the client sends the first event with Event Duration set to 160ms, then the second one with 320ms and then there is a huge gap until end of digit is detected and the final event is sent with Event Duration set to 1696ms or so.

This behavior is definitely not in accordance with the suggested procedure described in https://tools.ietf.org/html/rfc4733#section-2.5.1.2

On the other hand, the implementation should ideally be robust to be able to gracefully process this sort of deviations.

I would not be able to take a closer look at this any soon. Patches are welcome.
