### ISSUE TITLE
configure: error: Only installed dir location is supported now

### ISSUE THREAD

**Issue by MrityunjoyS** [unispeech/asterisk-unimrcp#48]
I  tried running the command `sudo apt-get install unimrcp-client-dev` first. But it's giving below error ->

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package unimrcp-client-dev

Same goes for `sudo apt-get install asterisk-app-unimrcp`. Error ->

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package asterisk-app-unimrcp

And for `sudo apt-get install asterisk-res-speech-unimrcp`. Error ->

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package asterisk-res-speech-unimrcp

Need your help. Thanks in advance

**Comment by achaloyan** [comment]
You may need to add the UniMRCP repository. Follow the [Installation Guide](http://unimrcp.org/manuals/pdf/AsteriskDebInstallationManual.pdf)

**Comment by MrityunjoyS** [comment]
Hi @achaloyan , as I've mentioned in my other issue, I've installed unimrcp-master branch successfully. Asterisk 16, is already installed. And I'm using Ubuntu-18.04.5-LTS as OS.
 
But after that, tryng to install `asterisk-app-unimrcp` and `asterisk-res-speech-unimrcp`  but getting above mentioned error.

**Comment by MohamedElrefai** [comment]
I am facing the same issue how did you solve it ?
I am using asterisk 18 and ubuntu 20.04 LTS
