### ISSUE TITLE
error while loading shared libraries: libsofia-sip-ua.so.0

### ISSUE THREAD

**Issue by MrityunjoyS** [unispeech/asterisk-unimrcp#49]
I've installed unimrcp-master branch successfully. Asterisk 16, is already installed.
But while I'm trying to Test the setup using below command :-

`./unimrcpserver
`
Getting below error :-

> ./unimrcpserver: error while loading shared libraries: libsofia-sip-ua.so.0: cannot open shared object file: No such file or directory

**Comment by achaloyan** [comment]
Use `ldconfig`
If it does help inspect the library path with `ldd /opt/unimrcp/bin/unimrcpserver `

**Comment by MrityunjoyS** [comment]
@achaloyan , thanks for the quick response. After using `ldconfig` I'm able to run above command.


> If it does help inspect the library path with `ldd /opt/unimrcp/bin/unimrcpserver`

But when running this command I'm getting no such file or directory ->

> /usr/local/unimrcp/bin# ldd /opt/unimrcp/bin/unimrcpserver
> ldd: /opt/unimrcp/bin/unimrcpserver: No such file or directory
