### ISSUE TITLE
app_MRCPRecord for mrcp recorder capabilities

### ISSUE THREAD

**Issue by mohit-dhiman** [unispeech/asterisk-unimrcp#51]
Hi, 
There is no `app_MRCPRecord` for using the **recorder** MRCP resource.
Is this deliberate or is it something that is in pipeline or it can be achieved using the already available apps or someone has to implement their own `app_MRCPRecord` to use this functionality.
Thank you

**Comment by achaloyan** [comment]
Hi Mohit,

The recorder resource is not widely used as the speech recognizer and synthesizer resources. But you are welcome to implement a new MRCPRecord application which would be very similar to the implementation of MRCPRecog.
