### ISSUE TITLE
MRCPRecog result is truncated if length > 1000

### ISSUE THREAD

**Issue by jbaumgarten** [unispeech/asterisk-unimrcp#60]
Hello,

I'm running an AGI script on asterisk which uses the MRCPRecog method. Everything works fine except when the result length is over 1000 caracters.
Is there any limitation on the result length?

Yours sincerely,
Julien

**Comment by jbaumgarten** [comment]
Issue seems not to be in unimrcp part but aster/agi

**Comment by achaloyan** [comment]
You may consider using helper function RECOG_INSTANCE() to retrieve individual fields in NLSML instance and/or RECOG_INPUT() for the input.
