### ISSUE TITLE
Invalid flags masks

### ISSUE THREAD

**Issue by bsixto** [unispeech/asterisk-unimrcp#7]
The rigth formt to set the bits for the flags masks is (from the Voximal fork):

	MRCPSYNTH_PROFILE        = (1 << 0),
	MRCPSYNTH_INTERRUPT      = (1 << 1),
	MRCPSYNTH_FILENAME       = (1 << 2),
	MRCPSYNTH_KEEPSESSION    = (1 << 3),
	MRCPSYNTH_ASTERISKVOLUME = (1 << 4),
	MRCPSYNTH_SENDDTMF       = (1 << 5)

and not

	MRCPSYNTH_PROFILE        = (1 << 0),
	MRCPSYNTH_INTERRUPT      = (2 << 0),
	MRCPSYNTH_FILENAME       = (3 << 0)

**Comment by achaloyan** [comment]
Thanks, Borja. Good catch, not sure how this bug survived till this point. 

Fixed in e2b0ef3bd41a8a0d878f77408315b28ebbe38e34
