### ISSUE TITLE
SPEECH_CHANNEL_TIMEOUT_USEC is not enough to load large grammars

### ISSUE THREAD

**Issue by Userator** [unispeech/asterisk-unimrcp#8]
The process of loading a large grammar takes place with the error "Unable to load grammar"

For 16mb grammar, 30 seconds of the timeout for downloading specified in SPEECH_CHANNEL_TIMEOUT_USEC is not sufficient.

Please add the feature, using the config, set the value for SPEECH_CHANNEL_TIMEOUT_USEC

**Comment by achaloyan** [comment]
This issue has been addressed in pull request #9.

**Comment by Userator** [comment]
Thank you so much
